---
- name: all vpc playbooks
  hosts: localhost
  tasks: 


- name: Create Vpc
  include: vpc.yaml

- name: Create Pub Subnets
  include: public-sub.yaml

- name: Create IGW
  include: internet-gateway.yaml

- name: Create Priv Subnets
  include: private-sub.yaml

- name: Create  Nat Gateway
  include: nat-gateway.yaml

- name: Create RT
  include: route-table-priv.yaml

- name: Create RT
  include: route-table-pub.yaml