---
- hosts: localhost
  vars_files: 
  - input.yaml
  tasks: 
  - name: Set up public subnet route table
    ec2_vpc_route_table:
      vpc_id: "{{vpc_id}}"
      region: "{{region}}"
      tags:
        Name: Public
      subnets:
        - "{{public_subnet_1}}"
        - "{{public_subnet_2}}"
        - "{{public_subnet_3}}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{igw.gateway_id}}"
 

  - name: Set up NAT-protected route table
    ec2_vpc_route_table:
      vpc_id: "{{vpc_id}}"
      region: "{{region}}"
      tags:
        Name: Internal
      subnets:
        - "{{private_subnet_1}"
        - "{{private_subnet_2}"
        - "{{private_subnet_3}"
      routes:
        - dest: 0.0.0.0/0
          instance_id: "{{nat.instance_id}}"